### ISSUE TITLE
Can't run the example due to exceptions in nodes

### ISSUE THREAD

**Issue by LorenzoBettini** [msanand/docker-workflow#1]
Hi, I was just trying your example, after reading your blog post; but running docker-compose up results in the nodes terminate with exceptions:

``````
Attaching to dockerworkflow_redis_1, dockerworkflow_node2_1, dockerworkflow_node3_1, dockerworkflow_node1_1, dockerworkflow_nginx_1
redis_1 | [1] 02 Apr 12:50:47.707 # Warning: no config file specified, using the default config. In order to specify a config file use /usr/bin/redis-server /path/to/redis.conf
redis_1 |                 _._                                                  
redis_1 |            _.-``__ ''-._                                             
redis_1 |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
redis_1 |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1 |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1 |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1 |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1 |  |    `-._`-._        _.-'_.-'    |                                  
redis_1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1 |       `-._    `-.__.-'    _.-'                                       
redis_1 |           `-._        _.-'                                           
redis_1 |               `-.__.-'                                               
redis_1 | 
redis_1 | [1] 02 Apr 12:50:47.708 # Server started, Redis version 2.8.4
redis_1 | [1] 02 Apr 12:50:47.708 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1 | [1] 02 Apr 12:50:47.709 * The server is now ready to accept connections on port 6379
node2_1 | 2 Apr 12:50:48 - [nodemon] v1.3.7
node2_1 | 2 Apr 12:50:48 - [nodemon] to restart at any time, enter `rs`
node2_1 | 2 Apr 12:50:48 - [nodemon] watching: *.*
node2_1 | 2 Apr 12:50:48 - [nodemon] starting `node /src/index.js`
node2_1 | 
node2_1 | module.js:340
node2_1 |     throw err;
node2_1 |           ^
node2_1 | Error: Cannot find module 'express'
node2_1 |     at Function.Module._resolveFilename (module.js:338:15)
node2_1 |     at Function.Module._load (module.js:280:25)
node2_1 |     at Module.require (module.js:364:17)
node2_1 |     at require (module.js:380:17)
node2_1 |     at Object.<anonymous> (/src/index.js:1:77)
node2_1 |     at Module._compile (module.js:456:26)
node2_1 |     at Object.Module._extensions..js (module.js:474:10)
node2_1 |     at Module.load (module.js:356:32)
node2_1 |     at Function.Module._load (module.js:312:12)
node2_1 |     at Function.Module.runMain (module.js:497:10)
node2_1 | 2 Apr 12:50:48 - [nodemon] app crashed - waiting for file changes before starting...
node3_1 | 2 Apr 12:50:50 - [nodemon] v1.3.7
node3_1 | 2 Apr 12:50:50 - [nodemon] to restart at any time, enter `rs`
node3_1 | 2 Apr 12:50:50 - [nodemon] watching: *.*
node3_1 | 2 Apr 12:50:50 - [nodemon] starting `node /src/index.js`
node3_1 | 
node3_1 | module.js:340
node3_1 |     throw err;
node3_1 |           ^
node3_1 | Error: Cannot find module 'express'
node3_1 |     at Function.Module._resolveFilename (module.js:338:15)
node3_1 |     at Function.Module._load (module.js:280:25)
node3_1 |     at Module.require (module.js:364:17)
node3_1 |     at require (module.js:380:17)
node3_1 |     at Object.<anonymous> (/src/index.js:1:77)
node3_1 |     at Module._compile (module.js:456:26)
node3_1 |     at Object.Module._extensions..js (module.js:474:10)
node3_1 |     at Module.load (module.js:356:32)
node3_1 |     at Function.Module._load (module.js:312:12)
node3_1 |     at Function.Module.runMain (module.js:497:10)
node3_1 | 2 Apr 12:50:50 - [nodemon] app crashed - waiting for file changes before starting...
node1_1 | 2 Apr 12:50:51 - [nodemon] v1.3.7
node1_1 | 2 Apr 12:50:51 - [nodemon] to restart at any time, enter `rs`
node1_1 | 2 Apr 12:50:51 - [nodemon] watching: *.*
node1_1 | 2 Apr 12:50:51 - [nodemon] starting `node /src/index.js`
node1_1 | 
node1_1 | module.js:340
node1_1 |     throw err;
node1_1 |           ^
node1_1 | Error: Cannot find module 'express'
node1_1 |     at Function.Module._resolveFilename (module.js:338:15)
node1_1 |     at Function.Module._load (module.js:280:25)
node1_1 |     at Module.require (module.js:364:17)
node1_1 |     at require (module.js:380:17)
node1_1 |     at Object.<anonymous> (/src/index.js:1:77)
node1_1 |     at Module._compile (module.js:456:26)
node1_1 |     at Object.Module._extensions..js (module.js:474:10)
node1_1 |     at Module.load (module.js:356:32)
node1_1 |     at Function.Module._load (module.js:312:12)
node1_1 |     at Function.Module.runMain (module.js:497:10)
node1_1 | 2 Apr 12:50:51 - [nodemon] app crashed - waiting for file changes before starting...
``````

**Comment by msanand** [comment]
Hi Lorenzo,

The error you are getting should only occur if the 'express' module was installed only globally and not locally. This shouldn't happen since I've included express as an app dependency in package.json.

Could you please pull the latest changes in my repository and then try rebuilding the images and running docker-compose again?

Rebuild images:
`docker-compose build`

Then:
`docker-compose up`.

Please let me know the results.

I've also made some changes to the Dockerfiles, each container taking a different approach to building the image. So please make sure you pull the latest code. I've also updated [the blog post](http://anandmanisankar.com/posts/docker-container-nginx-node-redis-example/) explaining the changes done.

Anand

**Comment by LorenzoBettini** [comment]
Hi Anand

I did pull the latest changes, rebuilt, and the problem is still there I'm afraid

**Comment by longieirl** [comment]
I'm experiencing the same issue, going to rebuild with 'volumes:        - node:/src' removed from the docker-compose.yml file, this seemed to resolve the issue! 

Want to see it working? Just run

```
curl $(boot2docker ip):80
```

**Comment by msanand** [comment]
Thanks for the PR @longieirl .
@LorenzoBettini : Since I'm unable to reproduce the issue you have reported, could you please confirm if the pull request resolves the problem? Thanks!

**Comment by LorenzoBettini** [comment]
I'm afraid the problem is still there, even after pulling the recent changes... I've also tried docker-compose build --no-cache, but the result is always the same...

Docker version 1.5.0, build a8a31ef

Linux OS

if there are any other experiments you want me to try...

**Comment by msanand** [comment]
Hi @LorenzoBettini ,
Could you please try the following:
Delete all existing containers created by docker-compose: 
`docker rm <container-id>` (For the 3 redis, 1 node and 1 nginx container)

Then trigger a re-build and re-create containers: `docker-compose build` followed by `docker-compose up`. I want to make sure the containers are created afresh.

**Comment by longieirl** [comment]
@msanand yes, i think that is the solution. Not sure if there is a docker composer command to do this! ;-) 

```
docker rmi $(docker images -q)
```

**Comment by msanand** [comment]
@longieirl Yeah, too bad... Docker compose should do something abt it.

`docker rm $(docker ps -a -q)`

**Comment by LorenzoBettini** [comment]
Sorry for the delay: yes, removing the containers solved the problem! :)
Thanks!
